version: "3"

services:
  judge-server:
    build: .
    restart: always
    working_dir: /app
    volumes:
      - ./:/app/
    command: python3 api.py -c judge.yml
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://@redis:6379/0
      OSS_KEY: key
      OSS_SECRET: secret
      OSS_BUCKET_NAME: bucket
      OSS_ROLE_ARN: role_arn
  redis:
    image: redis
    ports:
      - "6379:6379"
