version: "3"

services:
  judge-server:
    build: .
    restart: always
    working_dir: /app/judge-server
    volumes:
      - ./:/app/judge-server
    command: bash
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OSS_KEY: key
      OSS_SECRET: secret
      OSS_BUCKET_NAME: bucket
      OSS_ROLE_ARN: role_arn
  redis:
    image: redis
    ports:
      - "6379:6379"
